# Generated by Django 3.2.16 on 2023-01-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230125_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='to_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
    ]
